lane :upload do
  pilot(
    ipa: "app.ipa",
    skip_waiting_for_build_processing: true,
    api_key: {
      key_id: ENV["FASTLANE_APPLE_API_KEY_ID"],
      issuer_id: ENV["FASTLANE_APPLE_API_ISSUER_ID"],
      key: ENV["FASTLANE_APPLE_API_KEY"],
    },
  )
end

lane :distribute do
  pilot(
    distribute_only: true,
    api_key: {
      key_id: ENV["FASTLANE_APPLE_API_KEY_ID"],
      issuer_id: ENV["FASTLANE_APPLE_API_ISSUER_ID"],
      key: ENV["FASTLANE_APPLE_API_KEY"],
    },
  )
end
