name: Upload to Testflight

on:
  workflow_dispatch:
  repository_dispatch:
    types: [expo_build_done]


jobs:
  publish:
    name: Upload to Testflight
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Setup expo
        uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
          expo-cache: true
      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: "bundler-vendor"
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}-v1
      - name: Cache yarn deps
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarndeps-${{ hashFiles('**/yarn.lock') }}-v1
      - name: Install gems
        run: bundle install
      - name: Install deps
        run: yarn install
      - name: Download artifact
        run: ./scripts/download-expo-artifact
      - name: Upload to Testflight
        env:
          FASTLANE_APPLE_API_KEY_ID: ${{ secrets.FASTLANE_APPLE_API_KEY_ID }}
          FASTLANE_APPLE_API_ISSUER_ID: ${{ secrets.FASTLANE_APPLE_API_ISSUER_ID }}
          FASTLANE_APPLE_API_KEY: ${{ secrets.FASTLANE_APPLE_API_KEY }}
        run: bundle e fastlane upload
